spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/transp
    username: postgres
    password: 12314
    driverClassName: org.postgresql.Driver
  flyway:
    user: postgres
    password: 12314
    schemas: public
    url: jdbc:postgresql://localhost:5432/transp
    locations: db/migration
jwt:
  secret: dimon
  expiration: 30m
  header: Authorization

server:
  port: 8189

