spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddlAuto:
  datasource:
    url: jdbc:postgresql://localhost:5432/transp
    username: postgres
    password: 12314
    driverClassName: org.postgresql.Driver
jwt:
  secret: dimon
  expiration: 604800
  header: Authorization
